
export const IS_LOADING = 'IS_LOADING';
export const SET_APP_THEME = "SET_APP_THEME";
export const USER_INFO = 'USER_INFO'
export const USER_LOGOUT = 'USER_LOGOUT'
export const GET_CITY_DATA = 'GET_CITY_DATA'
export const GET_CUISINES_DATA = 'GET_CUISINES_DATA'
export const GET_CHEFS_DATA = 'GET_CHEFS_DATA'
export const DELETE_MENU_DATA = 'DELETE_MENU_DATA'
export const GET_MENU_DATA = 'GET_MENU_DATA'
export const SEARCH_CITY = 'SEARCH_CITY'
export const SELECT_ROLE = 'SELECT_ROLE'
export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE'
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const DELETE_CHEF_DATA = 'DELETE_CHEF_DATA'
export const DELETE_CUISINES_DATA ='DELETE_CUISINES_DATA'

export const GET_UNIVERSITIES_LIST ='GET_UNIVERSITIES_LIST'
export const GET_UNIVERSITIES_CANTEEN_LIST ='GET_UNIVERSITIES_CANTEEN_LIST'
export const GET_CANTEEN_MENU_LIST ='GET_CANTEEN_MENU_LIST'
