export const Icons = {
  launch_screen: require('../assets/Images/launch_screen.png'),
  onboardingW1: require('../assets/Images/w1.png'),
  bgLogin: require('../assets/Images/bgLogin.png'),
  ellipse: require('../assets/Images/ellipse.png'),
  vector: require('../assets/Images/vector.png'),
  location: require('../assets/Images/location.png'),
  slider1: require('../assets/Images/slider1.png'),
  profileImage: require('../assets/Images/profileImage.png'),



  //ICON
  apple: require('../assets/Icons/apple.png'),
  twitter: require('../assets/Icons/twitter.png'),
  google: require('../assets/Icons/googleIcon.png'),
  back: require('../assets/Icons/back.png'),
  eyeIn: require('../assets/Icons/eyeOn.png'),
  eyeOff: require('../assets/Icons/eyeOff.png'),
  facebook: require('../assets/Icons/facebook.png'),
  mapPin: require('../assets/Icons/mapPin.png'),
  home: require('../assets/Icons/home.png'),
  menuTab: require('../assets/Icons/menuTab.png'),
  notification: require('../assets/Icons/notification.png'),
  profile: require('../assets/Icons/profile.png'),
  addmenu: require('../assets/Icons/addmenu.png'),
  cart: require('../assets/Icons/cart.png'),
  leftMenu: require('../assets/Icons/leftMenu.png'),
  arrow_down: require('../assets/Icons/arrow_down.png'),
  ic_back: require('../assets/Icons/ic_back.png'),
  down: require('../assets/Icons/down.png'),
  chartBg: require('../assets/Icons/chartBg.png'),
  star: require('../assets/Icons/star.png'),
  option: require('../assets/Icons/option.png'),
  addImage: require('../assets/Icons/addImage.png'),
  locationPin: require('../assets/Icons/location_pin.png'),
  profileIcon: require('../assets/Icons/profile_Icon.png'),
  rightBack: require('../assets/Icons/right_back.png'),
  addresses: require('../assets/Icons/addresses.png'),
  menuIcon: require('../assets/Icons/menuIcon.png'),
  inventory: require('../assets/Icons/inventory.png'),
  bellIcon: require('../assets/Icons/bellIcon.png'),
  chefIcon: require('../assets/Icons/chefIcon.png'),
  faqsIcon: require('../assets/Icons/faqsIcon.png'),
  crmIcon: require('../assets/Icons/crmIcon.png'),
  settingsIcon: require('../assets/Icons/settingsIcon.png'),
  logout: require('../assets/Icons/logout.png'),
  optionIcon: require('../assets/Icons/optionIcon.png'),
  checkIcon: require('../assets/Icons/checkIcon.png'),
  close: require('../assets/Icons/close.png'),
  email: require('../assets/Icons/email.png'),
  phone: require('../assets/Icons/phone.png'),
  studentHome: require('../assets/Icons/studentHome.png'),
  editPencial: require('../assets/Icons/editPencial.png'),
  search: require('../assets/Icons/search.png'),
  plus: require('../assets/Icons/plus.png'),
  minus: require('../assets/Icons/minus.png'),
  cart1: require('../assets/Icons/cart1.png'),
  delete: require('../assets/Icons/delete.png'),
  cuisine: require('../assets/Icons/cuisine.png'),
  chef: require('../assets/Icons/chef.png'),
  addMenu1: require('../assets/Icons/addMenu1.png'),
  leftback: require('../assets/Icons/leftback.png'),
  left_menu: require('../assets/Icons/left_menu.png'),
  drop_down: require('../assets/Icons/drop_down.png'),
  runnigIcon: require('../assets/Icons/runnigIcon.png'),
  orderIcon: require('../assets/Icons/orderIcon.png'),
};
